# Stage 1: Build Angular App
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build --prod

FROM nginx:alpine


RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist/* /usr/share/nginx/html/


EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
