# Build stage
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /src
COPY . . 
RUN dotnet restore graduationproject.sln
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:7.0  AS runtime

WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8000


ENTRYPOINT ["dotnet", "graduationproject.dll","migrate"]